### ISSUE TITLE
New deployment doesn't link assets correctly. 

### ISSUE THREAD

**Issue by corymacd** [flareact/flareact-template#6]
newly generated iteration of this template,  no changes other than configuration, a yarn dev works as expected, while a yarn publish (or npm publish) results in console errors: 

Notice the clearly missing '/' between the static and main, static and pages. 

GET https://domain/_flareact/staticmain.810a2c111de41785fa76.js net::ERR_ABORTED 500
domain/:1 GET https://doman/_flareact/staticpages/_app.6dd38c9612d4d82586f9.js net::ERR_ABORTED 500

**Comment by maguayo** [comment]
@corymacd did you solve the issue? I have the same problem
